apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: dev-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: mypagecontainer
          image: maheshravaji/mylandingpageweb:latest  # Use the correct image tag
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: myregistrykey
