apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: dev-namespace

spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
  type: NodePort
